-- 001_initial_schema.sql — the v2 baseline schema.
--
-- Extracted verbatim from the SCHEMA constant that src/db.js used to exec inline.
-- SE-101 requires migrations in versioned files rather than inline DDL, so this is
-- the starting point of the history, not a change to it: on a database that already
-- exists every statement is a no-op, and on a fresh one it reproduces exactly what
-- ingest and geocode were built against.
--
-- Do not edit this file. The runner records a checksum per migration and refuses to
-- proceed if an applied one changes; corrections belong in a later numbered file.
CREATE TABLE IF NOT EXISTS establishment (
  -- license_key + normalized_address. The two extracts disagree about identity:
  -- the licence file has no License ID and its License Number is not unique
  -- (SEA6021991 covers two businesses at one address, different suites), so the
  -- address is needed to keep both. See MVP-SE-001 §4 and DEC-006.
  establishment_id    TEXT PRIMARY KEY,
  -- '<digits>|<licenseTypeCode>' — the join key to inspection.
  -- The licence file writes "SEA6021991"; the inspection file writes "6021991".
  -- Joining on the raw strings matches ZERO rows. Do not "simplify" this away.
  license_key         TEXT NOT NULL,
  license_number      TEXT,
  name                TEXT NOT NULL,
  address             TEXT,
  normalized_address  TEXT,
  city                TEXT,
  zip                 TEXT,
  county_code         TEXT,
  county_name         TEXT,
  district            TEXT,
  license_type_code   TEXT,
  seats               INTEGER,
  risk_level          TEXT,
  -- geocode.js only. Never in an ingest upsert column list.
  lat                 REAL,
  lng                 REAL,
  geocode_source      TEXT,
  geocode_quality     TEXT,
  first_seen_at       TEXT,
  last_seen_at        TEXT
);

CREATE INDEX IF NOT EXISTS idx_est_bbox    ON establishment(lat, lng);
CREATE INDEX IF NOT EXISTS idx_est_norm    ON establishment(normalized_address);
CREATE INDEX IF NOT EXISTS idx_est_name    ON establishment(name);
CREATE INDEX IF NOT EXISTS idx_est_key     ON establishment(license_key);

CREATE TABLE IF NOT EXISTS inspection (
  -- "Inspection Visit ID", the only genuinely unique column in the extract.
  -- "Inspection Number" is a CASE id: one case carries several visits
  -- (e.g. visit 2 "Extension given, pending" then visit 3 "Complied").
  -- Keying on it collapsed 1,305 visits to 1,037 and lost the callback outcome,
  -- which is precisely what determines the current signal.
  inspection_visit_id TEXT PRIMARY KEY,
  inspection_number   TEXT,        -- case id; several visits share it
  license_key         TEXT,        -- joins establishment.license_key
  source_license_id   TEXT,        -- "License ID" as published in this extract
  inspection_date     TEXT,        -- ISO 8601; source is MM/DD/YYYY
  inspection_class    TEXT,
  inspection_type     TEXT,
  disposition         TEXT,        -- verbatim from source
  signal              TEXT,        -- derived; see src/signal.js
  visit_number        INTEGER,
  critical_violations     INTEGER,
  noncritical_violations  INTEGER,
  total_violations        INTEGER,
  high_violations         INTEGER,
  intermediate_violations INTEGER,
  basic_violations        INTEGER
);

CREATE INDEX IF NOT EXISTS idx_insp_key    ON inspection(license_key, inspection_date DESC);
CREATE INDEX IF NOT EXISTS idx_insp_date   ON inspection(inspection_date DESC);
CREATE INDEX IF NOT EXISTS idx_insp_case   ON inspection(inspection_number);

CREATE TABLE IF NOT EXISTS violation (
  inspection_visit_id TEXT NOT NULL,
  violation_code      TEXT NOT NULL,
  count               INTEGER,
  PRIMARY KEY (inspection_visit_id, violation_code)
);

CREATE INDEX IF NOT EXISTS idx_viol_insp   ON violation(inspection_visit_id);

CREATE TABLE IF NOT EXISTS geocode_cache (
  normalized_address  TEXT PRIMARY KEY,
  lat                 REAL,
  lng                 REAL,
  quality             TEXT,
  source              TEXT,
  resolved_at         TEXT
);

CREATE TABLE IF NOT EXISTS ingest_run (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  source_url          TEXT,
  dataset             TEXT,
  started_at          TEXT,
  finished_at         TEXT,
  status              TEXT,        -- 'success' | 'failed'
  rows_fetched        INTEGER,
  rows_after_filter   INTEGER,
  rows_written        INTEGER,
  failure_stage       TEXT,
  failure_reason      TEXT
);

CREATE INDEX IF NOT EXISTS idx_run_time    ON ingest_run(started_at DESC);
